[phases.setup]
nixPkgs = ['nodejs', 'npm']

[phases.install]
cmds = ['npm install --legacy-peer-deps']

[phases.build]
cmds = [
  'cd frontend && npm install --legacy-peer-deps',
  'cd frontend && npm run build',
  'cd ../backend && npm install --legacy-peer-deps'
]

[start]
cmd = 'npm start'